---
title: <span style="color:#034a94"> **Análisis de datos**</span>
author: "Métodos y Simulación Estadística"
output:
  html_document:
    toc: yes
    toc_depth: 2
    toc_float: yes
    theme: paper
css: style.css
---

```{r setup, include=FALSE}
knitr::opts_chunk$set(echo = TRUE, comment = NA)
library(readr)
library(tidyverse)
library(DT)
readRDS("/home/deg/Documentos/Javeriana/Ms en Ciencia de Datos/data/RioCali.RSD")

```

</br></br></br>

# **Representación de datos**

</br>

Una de las formas para organizar y resumir conjuntos grandes de datos es por medio de tablas y gráficas de frecuencias, dado que permiten condensar la información y facilitan la apreciación de su contenido. Pese a que ambas formas proporcionan información similar, cuando se desea transmitir una idea rápida y sencilla es preferible utilizar una gráfica de frecuencias; mientras que cuando se desea analizar los datos con mayor detenimiento o precisión, las tablas de frecuencias son más útiles.

</br></br>

Es posible construir una gran variedad de tablas y gráficas, sin embargo, en este momento solo se presentarán tablas y gráficas de frecuencia de una sola variable (una sola entrada) y sólo tres casos o tipos de tablas (datos categóricos, datos puntuales y datos agrupados), que pueden construirse a partir de un determinado conjunto de datos ya sea para una muestra o una población.



</br></br>

TABLERO??


