---
title: <span style="color:#034a94"> **Análisis de datos**</span>
author: "Métodos y Simulación Estadística"
output:
  html_document:
    toc: no
    toc_depth: 2
    toc_float: yes
    code_folding: hide
    css: style.css
---

```{r setup, include=FALSE}
knitr::opts_chunk$set(echo = TRUE, comment = NA)
library(readr)
library(tidyverse)
library(DT)
library(paqueteMETODOS)

data("CarreraLuz22")
data("evaluacion")
data("inflacionov22")
```

</br>

# <span style="color:#034a94">**Representación de datos**</span> 

</br>

Una de las formas para organizar y resumir conjuntos grandes de datos es por medio de tablas y gráficas de frecuencias, dado que permiten condensar la información y facilitan la apreciación de su contenido. Pese a que ambas formas proporcionan información similar, cuando se desea transmitir una idea rápida y sencilla es preferible utilizar una gráfica de frecuencias; mientras que cuando se desea analizar los datos con mayor detenimiento o precisión, las tablas de frecuencias son más útiles.

<br/>

Estos indicadores y gráficos pueden formar parte de informes estadísticos, tableros, posters o infografías. 

El siguiente tablero, permite visualizar en tiempo real los paquetes de R que se están descargando. El tamaño del los circulos representan las frecuencias de cada uno de ellos, haciendo que los que se representan por circulos más grandes tengan una mayor frecuencia.

</br><br/>

<iframe src="https://testing-apps.shinyapps.io/flexdashboard-shiny-crandash/" width="1000" height="800"></iframe>

<center>
<sub>
Fuente : Tomado de [CRAN Download Monitor](https://testing-apps.shinyapps.io/flexdashboard-shiny-crandash)
</sub>
</center>

<br/>


